// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-TQZfV2lUWSChD4-lS2iJbd0Q6G1tjSY',
    appId: '1:361679524416:web:151a214e7800edad9785a5',
    messagingSenderId: '361679524416',
    projectId: 'rare-crew-task',
    authDomain: 'rare-crew-task.firebaseapp.com',
    storageBucket: 'rare-crew-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRK2zO4OHmYr0X8MHYGO3Fm0K_17TRWL8',
    appId: '1:361679524416:android:da21c530ac9360f89785a5',
    messagingSenderId: '361679524416',
    projectId: 'rare-crew-task',
    storageBucket: 'rare-crew-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1Tc5VkYPiXXlWC3QYXZC_cqwHD8k9XY',
    appId: '1:361679524416:ios:9f5d65ec0057b5389785a5',
    messagingSenderId: '361679524416',
    projectId: 'rare-crew-task',
    storageBucket: 'rare-crew-task.firebasestorage.app',
    iosClientId: '361679524416-f80cc917jcejr9761ihsmj9cnm7iraj6.apps.googleusercontent.com',
    iosBundleId: 'com.RareCrew.testRarecrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-TQZfV2lUWSChD4-lS2iJbd0Q6G1tjSY',
    appId: '1:361679524416:web:db257a97e59edcc79785a5',
    messagingSenderId: '361679524416',
    projectId: 'rare-crew-task',
    authDomain: 'rare-crew-task.firebaseapp.com',
    storageBucket: 'rare-crew-task.firebasestorage.app',
  );

}